export function getIngredientEmoji(name: string): string | null {
  if (!name) return null;
  const normalized = name.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g, "");

  const partialMatches: { match: string[], emj: string }[] = [
    { match: ["leite em po", "formula", "mucilon", "nestogeno", "leite materno", "nan "], emj: "🍼" },
    { match: ["leite condensado", "creme de leite", "doce de leite", "pudim", "flan", "mousse", "gelatina", "maria mole"], emj: "🍮" },
    { match: ["leite"], emj: "🥛" },
    { match: ["queijo", "mussarela", "mozzarella", "parmesao", "prato", "provolone", "gorgonzola", "cheddar", "brie", "ricota", "coalho", "catupiry", "minas"], emj: "🧀" },
    { match: ["manteiga", "margarina", "requeijao", "cream cheese", "gordura", "banha"], emj: "🧈" },
    { match: ["pao de queijo", "pao de forma", "ciabatta", "croissant", "medialuna"], emj: "🥐" },
    { match: ["pao", "torrada", "baguete", "bisnaga", "brioche", "fermento natural"], emj: "🍞" },
    { match: ["panqueca", "waffle", "tapioca"], emj: "🥞" },
    { match: ["bolo", "torta", "brownie", "muffin", "cupcake", "cheesecake", "panetone", "chocotone"], emj: "🍰" },
    { match: ["rosquinha", "donut", "sonho", "churro"], emj: "🍩" },
    { match: ["biscoito", "bolacha", "cookie", "wafer", "oreo", "maizena", "agua e sal"], emj: "🍪" },
    { match: ["chocolate", "cacau", "achocolatado", "nescau", "toddy", "bombom", "trufa", "nutella"], emj: "🍫" },
    { match: ["acucar", "adocante", "bala", "chiclete", "jujuba", "caramelo"], emj: "🍬" },
    { match: ["mel", "melado", "xarope"], emj: "🍯" },
    { match: ["sorvete", "picole", "gelato", "acai", "frozen"], emj: "🍨" },
    { match: ["raspadinha"], emj: "🍧" },
    { match: ["bacon", "porco", "pernil", "lombo", "costelinha", "toucinho", "torresmo", "panceta"], emj: "🥓" },
    { match: ["presunto", "apresuntado", "mortadela", "salame", "peito de peru", "blanquet", "defumado", "copa", "prosciutto", "fiambre"], emj: "🍖" },
    { match: ["linguica", "salsicha", "calabresa", "paio", "hot dog"], emj: "🌭" },
    { match: ["frango", "coxa", "peito", "sobrecoxa", "galinha", "ave", "peru", "chester"], emj: "🍗" },
    { match: ["carne", "bife", "picanha", "alcatra", "patinho", "contra file", "costela", "maminha", "acem", "picadinho", "mignon", "fraldinha", "cupim"], emj: "🥩" },
    { match: ["osso", "mocoto"], emj: "🦴" },
    { match: ["peixe", "salmao", "atum", "sardinha", "tilapia", "bacalhau", "merluza", "pescada", "pintado", "tambaqui", "anchova"], emj: "🐟" },
    { match: ["camarao", "marisco", "lula", "polvo", "frutos do mar"], emj: "🍤" },
    { match: ["caranguejo", "siri"], emj: "🦀" },
    { match: ["ostra", "mexilhao"], emj: "🦪" },
    { match: ["ovo", "ovos", "gema", "clara", "codorna"], emj: "🥚" },
    { match: ["arroz", "risoto", "arborio"], emj: "🍚" },
    { match: ["feijao", "grao de bico", "ervilha", "lentilha", "soja", "fava", "feijoada"], emj: "🫘" },
    { match: ["macarrao", "espaguete", "massa", "nhoque", "lasanha", "penne", "parafuso", "miojo", "fettuccine", "talharim"], emj: "🍝" },
    { match: ["ramen", "lamen", "sopa de macarrao", "udon", "soba"], emj: "🍜" },
    { match: ["sopa", "caldo", "ensopado", "sucrilhos", "cereal", "granola", "mingau", "aveia em flocos"], emj: "🥣" },
    { match: ["farinha", "trigo", "fuba", "polvilho", "amido", "maisena", "aveia", "farelo", "cereais", "cevada", "centeio"], emj: "🌾" },
    { match: ["amendoim", "castanha", "noz", "nozes", "amendoa", "avela", "macadamia", "pistache", "peca", "pinhao", "pasta de amendoim"], emj: "🥜" },
    { match: ["tomate", "molho de tomate", "pomodoro", "ketchup", "extrato de tomate"], emj: "🍅" },
    { match: ["cenoura", "baby carrot"], emj: "🥕" },
    { match: ["milho", "espiga", "pipoca", "canjica", "pamonha"], emj: "🌽" },
    { match: ["brocolis", "couve-flor"], emj: "🥦" },
    { match: ["alface", "couve", "rucula", "escarola", "acelga", "agriao", "repolho", "espinafre", "chicoria"], emj: "🥬" },
    { match: ["pepino", "abobrinha", "chuchu", "quiabo", "maxixe"], emj: "🥒" },
    { match: ["beringela", "berinjela", "jilo"], emj: "🍆" },
    { match: ["pimentao"], emj: "🫑" },
    { match: ["pimenta", "malagueta", "dedo de moca", "jalapeno", "tabasco"], emj: "🌶️" },
    { match: ["cebola roxa", "chalota", "cebola"], emj: "🧅" },
    { match: ["alho", "puro alho", "dente de alho"], emj: "🧄" },
    { match: ["batata doce", "inhame", "cara"], emj: "🍠" },
    { match: ["batata", "mandioca", "aipim", "macaxeira", "batata frita", "pure"], emj: "🥔" },
    { match: ["cogumelo", "champignon", "shitake", "shimeji", "funghi"], emj: "🍄" },
    { match: ["maca", "macã"], emj: "🍎" },
    { match: ["pera", "pêra"], emj: "🍐" },
    { match: ["laranja", "mexerica", "tangerina", "bergamota", "ponkan"], emj: "🍊" },
    { match: ["limao", "lima"], emj: "🍋" },
    { match: ["banana", "prata", "nanica", "da terra", "pacovan"], emj: "🍌" },
    { match: ["melancia"], emj: "🍉" },
    { match: ["uva", "passa", "uvas"], emj: "🍇" },
    { match: ["morango", "framboesa", "amora", "mirtilo", "blueberry"], emj: "🍓" },
    { match: ["melao"], emj: "🍈" },
    { match: ["cereja"], emj: "🍒" },
    { match: ["pessego", "nectarina", "ameixa", "damasco"], emj: "🍑" },
    { match: ["abacaxi"], emj: "🍍" },
    { match: ["kiwi"], emj: "🥝" },
    { match: ["abacate", "avocado", "guacamole"], emj: "🥑" },
    { match: ["coco", "leite de coco", "agua de coco"], emj: "🥥" },
    { match: ["manga", "maracuja", "mamao", "goiaba", "caju", "cacau", "umbu", "siriguela", "cupuacu", "graviola", "acerola", "pitanga"], emj: "🥭" },
    { match: ["sal grosso", "sal rosa", "sal"], emj: "🧂" },
    { match: ["pimenta do reino", "colorau", "cominho", "paprica", "acafrao", "noz moscada", "canela", "cravo", "oregano", "curry", "tempero", "ajinomoto", "condimento"], emj: "🍂" },
    { match: ["cebolinha", "salsinha", "coentro", "tempero verde", "cheiro verde", "hortela", "manjericao", "alecrim", "louro", "tomilho", "ervas"], emj: "🌿" },
    { match: ["azeitona", "azeite"], emj: "🫒" },
    { match: ["oleo", "fritura", "azeite de dende"], emj: "🛢️" },
    { match: ["maionese", "mostarda", "picles", "molho branco", "molho ingles", "shoyu", "vinagre", "palmito", "milho em conserva", "ervilha em conserva", "salsaretti", "atum em lata", "sardinha em lata", "creme de leite em lata", "leite condensado em lata", "molho", "conserva"], emj: "🥫" },
    { match: ["agua mineral", "agua com gas", "agua", "gelo"], emj: "💧" },
    { match: ["cafe", "expresso", "cappuccino", "mocaccino", "cafe soluvel"], emj: "☕" },
    { match: ["cha", "mate", "chimarrao", "erva mate", "infusao", "kombucha"], emj: "🍵" },
    { match: ["suco", "limonada", "nectar", "toddynho", "kapo"], emj: "🧃" },
    { match: ["refrigerante", "refri", "coca", "guarana", "pepsi", "fanta", "sprite", "soda"], emj: "🥤" },
    { match: ["cerveja", "chopp", "ipa", "pilsen", "lager", "stout"], emj: "🍺" },
    { match: ["vinho", "champanhe", "espumante", "merlot", "cabernet"], emj: "🍷" },
    { match: ["cachaca", "pinga", "vodka", "gin", "rum", "whisky", "licor", "tequila", "conhaque", "alcool"], emj: "🥃" },
    { match: ["drink", "cocktail", "caipirinha", "mojito"], emj: "🍹" },
    { match: ["gelo"], emj: "🧊" },
    { match: ["iogurte", "yakult", "danone", "danoninho"], emj: "🍦" },
    { match: ["hamburger", "hamburguer", "burguer"], emj: "🍔" },
    { match: ["pizza"], emj: "🍕" },
    { match: ["taco", "nacho", "tortilla"], emj: "🌮" },
    { match: ["sushi", "sashimi", "temaki"], emj: "🍣" },
    { match: ["salada", "mix de folhas", "rúcula"], emj: "🥗" },
    { match: ["fermento", "bicarbonato", "sabao", "detergente", "amaciante", "desinfetante", "agua sanitaria", "cloro", "limpeza", "veja", "omo", "candida"], emj: "🫧" },
    { match: ["papel higienico", "papel toalha", "guardanapo", "lenco"], emj: "🧻" },
    { match: ["esponja", "bucha", "bombril"], emj: "🧽" },
    { match: ["vassoura", "rodo"], emj: "🧹" },
    { match: ["lixo", "saco de lixo"], emj: "🗑️" }
  ];

  for (const { match, emj } of partialMatches) {
    if (match.some((keyword) => normalized.includes(keyword))) {
      return emj;
    }
  }

  // Devolve nulo para os não conhecidos a fim de dar espaço para a IA agir!
  return null; 
}
